name: Run unit tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test_config:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Test config package
        run: |
          DEPS="$(go list -deps ./...|grep 'fredbi/gflag')"
          go test \
              -v \
              -coverprofile=cover.out \
              -covermode=atomic \
              -coverpkg="$(echo ${DEPS}|sed -E '1,$s/\s/,/g')" \
              ./...

      - name: Prepare coverage output
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
